<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class ProfessionalCatalogSeeder extends Seeder
{
    /**
     * Catálogo profesional: un producto por cada categoría existente.
     * Las imágenes deben existir en storage/app/public/products con
     * el nombre indicado en la clave 'image'.
     */
    public function run(): void
    {
        $categories = Category::all()->keyBy('name');

        $products = [
            [
                'name' => 'Tenis Nike Air Zoom Pegasus 40',
                'brand' => 'Nike',
                'model' => 'Air Zoom Pegasus 40',
                'price' => 2899.00,
                'description' => 'Tenis de running con amortiguación Air Zoom reactiva y malla transpirable de ingeniería. Ideal para entrenamientos diarios y corredores de todos los niveles que buscan comodidad y respuesta en cada pisada.',
                'stock' => 30,
                'category' => 'Calzado Deportivo',
                'image' => 'catalogo-calzado.jpg',
                'sizes' => ['25', '26', '27', '28', '29', '30'],
                'colors' => ['Negro', 'Blanco', 'Rojo'],
                'material' => 'Mesh sintético y espuma',
                'gender' => 'unisex',
                'sport_type' => 'Running',
                'weight' => 0.62,
                'specifications' => ['Suela' => 'Caucho antideslizante', 'Amortiguación' => 'Air Zoom', 'Drop' => '10 mm'],
                'is_featured' => true,
                'sku' => 'NIK-PEG40-001',
            ],
            [
                'name' => 'Playera Casual Estampado Original',
                'brand' => 'Original',
                'model' => 'Gato Azul',
                'price' => 499.00,
                'description' => 'Playera casual de algodón con estampado original al frente. Corte clásico unisex de uso diario, suave al tacto y combinable con cualquier outfit deportivo o casual.',
                'stock' => 50,
                'category' => 'Ropa Deportiva',
                'image' => 'catalogo-ropa.jpg',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Beige'],
                'material' => 'Algodón',
                'gender' => 'unisex',
                'sport_type' => 'Casual',
                'weight' => 0.18,
                'specifications' => ['Tecnología' => 'Aeroready', 'Corte' => 'Atlético regular'],
                'is_featured' => true,
                'sku' => 'ADI-AER-PLA-002',
            ],
            [
                'name' => 'Balón de Fútbol Voit Profesional No. 5',
                'brand' => 'Voit',
                'model' => 'Profesional No. 5',
                'price' => 999.00,
                'description' => 'Balón de fútbol profesional tamaño No. 5 con cubierta de poliuretano de alta resistencia y cámara de butilo que retiene el aire por más tiempo. Vuelo estable y toque suave, apto para pasto natural y sintético.',
                'stock' => 40,
                'category' => 'Equipamiento de Fútbol',
                'image' => 'catalogo-futbol.jpg',
                'sizes' => [],
                'colors' => ['Blanco'],
                'material' => 'Poliuretano',
                'gender' => 'unisex',
                'sport_type' => 'Fútbol',
                'weight' => 0.45,
                'specifications' => ['Tamaño' => 'No. 5 oficial', 'Cámara' => 'Butilo', 'Uso' => 'Pasto natural y sintético'],
                'is_featured' => false,
                'sku' => 'VOI-BAL-5-003',
            ],
            [
                'name' => 'Balón de Basketball Spalding TF-1000',
                'brand' => 'Spalding',
                'model' => 'TF-1000',
                'price' => 1299.00,
                'description' => 'Balón de basketball para interior con cubierta de cuero compuesto premium que ofrece agarre superior y control total. Ranuras profundas para un drible preciso y tiro consistente en duela.',
                'stock' => 35,
                'category' => 'Equipamiento de Basketball',
                'image' => 'catalogo-basketball.jpg',
                'sizes' => [],
                'colors' => ['Naranja'],
                'material' => 'Cuero compuesto',
                'gender' => 'unisex',
                'sport_type' => 'Basketball',
                'weight' => 0.60,
                'specifications' => ['Tamaño' => 'No. 7 oficial', 'Uso' => 'Interior / duela', 'Cubierta' => 'Cuero compuesto'],
                'is_featured' => true,
                'sku' => 'SPA-TF1000-004',
            ],
            [
                'name' => 'Tenis Nike Air Force 1 07',
                'brand' => 'Nike',
                'model' => 'Air Force 1 07',
                'price' => 2599.00,
                'description' => 'El clásico tenis Nike Air Force 1 en color negro con unidad Air encapsulada en el talón y piel premium. Ícono del estilo urbano con tracción duradera para el día a día.',
                'stock' => 25,
                'category' => 'Calzado Deportivo',
                'image' => 'catalogo-running.jpg',
                'sizes' => ['25', '26', '27', '28', '29'],
                'colors' => ['Negro', 'Blanco'],
                'material' => 'Piel sintética',
                'gender' => 'unisex',
                'sport_type' => 'Casual',
                'weight' => 0.60,
                'specifications' => ['Amortiguación' => 'Nike Air', 'Corte' => 'Clásico bajo', 'Uso' => 'Diario'],
                'is_featured' => false,
                'sku' => 'ASI-EXC10-005',
            ],
            [
                'name' => 'Par de Mancuernas Hexagonales 5 kg',
                'brand' => 'ProForm',
                'model' => 'Hexagonal 5',
                'price' => 899.00,
                'description' => 'Par de mancuernas hexagonales de 5 kg con recubrimiento que evita que rueden y protege el piso. Agarre ergonómico de acero para rutinas de fuerza en casa o gimnasio.',
                'stock' => 20,
                'category' => 'Equipamiento de Fitness',
                'image' => 'catalogo-fitness.jpg',
                'sizes' => [],
                'colors' => ['Negro'],
                'material' => 'Hierro con recubrimiento',
                'gender' => 'unisex',
                'sport_type' => 'Fitness',
                'weight' => 10.00,
                'specifications' => ['Peso' => '5 kg por mancuerna', 'Forma' => 'Hexagonal antirrodante', 'Agarre' => 'Ergonómico'],
                'is_featured' => true,
                'sku' => 'PFO-MAN24-006',
            ],
            [
                'name' => 'Goggles de Natación Speedo Hydrospex',
                'brand' => 'Speedo',
                'model' => 'Hydrospex',
                'price' => 549.00,
                'description' => 'Goggles de natación con lentes antivaho y protección UV, correa ajustable de silicón hipoalergénico y sellado cómodo que evita filtraciones. Visión panorámica para entrenamiento y recreación.',
                'stock' => 45,
                'category' => 'Deportes Acuáticos',
                'image' => 'catalogo-natacion.jpg',
                'sizes' => [],
                'colors' => ['Azul', 'Negro'],
                'material' => 'Silicón y policarbonato',
                'gender' => 'unisex',
                'sport_type' => 'Natación',
                'weight' => 0.08,
                'specifications' => ['Lentes' => 'Antivaho con protección UV', 'Correa' => 'Silicón ajustable', 'Uso' => 'Entrenamiento y recreación'],
                'is_featured' => false,
                'sku' => 'SPE-HYD-007',
            ],
            [
                'name' => 'Raqueta de Tenis Wilson Pro Staff 100',
                'brand' => 'Wilson',
                'model' => 'Pro Staff 100',
                'price' => 3899.00,
                'description' => 'Raqueta de tenis de 280 g con aro de 100 pulgadas cuadradas que combina potencia y control. Marco de grafito con tecnología de estabilidad para jugadores intermedios y avanzados.',
                'stock' => 15,
                'category' => 'Deportes de Raqueta',
                'image' => 'catalogo-raqueta.jpg',
                'sizes' => [],
                'colors' => ['Negro', 'Blanco'],
                'material' => 'Grafito',
                'gender' => 'unisex',
                'sport_type' => 'Tenis',
                'weight' => 0.28,
                'specifications' => ['Peso' => '280 g', 'Aro' => '100 pulgadas cuadradas', 'Balance' => '325 mm', 'Encordado' => '16x19'],
                'is_featured' => false,
                'sku' => 'WIL-PS100-008',
            ],
            [
                'name' => 'Reloj Deportivo Amazfit GTS 4 Mini',
                'brand' => 'Amazfit',
                'model' => 'GTS 4 Mini',
                'price' => 2799.00,
                'description' => 'Reloj inteligente deportivo con GPS integrado, monitoreo de frecuencia cardiaca, oxígeno en sangre y más de 120 modos deportivos. Batería de hasta 15 días y resistencia al agua 5 ATM.',
                'stock' => 20,
                'category' => 'Accesorios Deportivos',
                'image' => 'catalogo-accesorios.jpg',
                'sizes' => [],
                'colors' => ['Negro'],
                'material' => 'Aluminio y silicón',
                'gender' => 'unisex',
                'sport_type' => 'Fitness',
                'weight' => 0.05,
                'specifications' => ['Batería' => 'Hasta 15 días', 'Resistencia' => '5 ATM', 'GPS' => 'Integrado', 'Modos deportivos' => 'Más de 120'],
                'is_featured' => true,
                'sku' => 'AMA-GTS4M-009',
            ],
            [
                'name' => 'Casco de Ciclismo Giro Register MIPS',
                'brand' => 'Giro',
                'model' => 'Register MIPS',
                'price' => 1599.00,
                'description' => 'Casco de ciclismo con sistema de protección MIPS contra impactos rotacionales, 22 rejillas de ventilación y ajuste micrométrico. Ligero y cómodo para ruta y montaña.',
                'stock' => 22,
                'category' => 'Ciclismo',
                'image' => 'catalogo-ciclismo.jpg',
                'sizes' => ['M', 'L'],
                'colors' => ['Negro', 'Blanco', 'Rojo'],
                'material' => 'Policarbonato y EPS',
                'gender' => 'unisex',
                'sport_type' => 'Ciclismo',
                'weight' => 0.30,
                'specifications' => ['Protección' => 'Sistema MIPS', 'Ventilación' => '22 rejillas', 'Ajuste' => 'Micrométrico Roc Loc Sport'],
                'is_featured' => false,
                'sku' => 'GIR-REGM-010',
            ],
            [
                'name' => 'Tenis Puma RS-X Efekt',
                'brand' => 'Puma',
                'model' => 'RS-X Efekt',
                'price' => 2499.00,
                'description' => 'Tenis lifestyle con herencia running y entresuela RS de máxima amortiguación. Silueta robusta con detalles premium, perfectos para uso diario con estilo deportivo.',
                'stock' => 28,
                'category' => 'Calzado Deportivo',
                'image' => 'catalogo-calzado2.jpg',
                'sizes' => ['25', '26', '27', '28', '29', '30'],
                'colors' => ['Morado', 'Blanco', 'Naranja'],
                'material' => 'Mesh y sintético',
                'gender' => 'unisex',
                'sport_type' => 'Casual',
                'weight' => 0.65,
                'specifications' => ['Entresuela' => 'Tecnología RS', 'Suela' => 'Caucho', 'Uso' => 'Diario'],
                'is_featured' => true,
                'sku' => 'PUM-RSX-011',
            ],
            [
                'name' => 'Playera Nike Dri-FIT Básica',
                'brand' => 'Nike',
                'model' => 'Dri-FIT Básica',
                'price' => 649.00,
                'description' => 'Playera esencial de algodón con tecnología Dri-FIT que mantiene la frescura todo el día. Corte clásico unisex, básica indispensable para entrenar o vestir casual.',
                'stock' => 60,
                'category' => 'Ropa Deportiva',
                'image' => 'catalogo-ropa2.jpg',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Blanco', 'Negro', 'Gris'],
                'material' => 'Algodón y poliéster',
                'gender' => 'unisex',
                'sport_type' => 'Fitness',
                'weight' => 0.16,
                'specifications' => ['Tecnología' => 'Dri-FIT', 'Corte' => 'Clásico'],
                'is_featured' => false,
                'sku' => 'NIK-DFB-012',
            ],
            [
                'name' => 'Balón Adidas Champions League No. 5',
                'brand' => 'Adidas',
                'model' => 'Champions League',
                'price' => 1199.00,
                'description' => 'Balón oficial estilo Champions League tamaño No. 5 con paneles termosellados sin costuras para vuelo preciso y control excepcional. Superficie texturizada para mejor agarre en seco y mojado.',
                'stock' => 32,
                'category' => 'Equipamiento de Fútbol',
                'image' => 'catalogo-futbol2.jpg',
                'sizes' => [],
                'colors' => ['Blanco', 'Azul'],
                'material' => 'Poliuretano termosellado',
                'gender' => 'unisex',
                'sport_type' => 'Fútbol',
                'weight' => 0.43,
                'specifications' => ['Tamaño' => 'No. 5 oficial', 'Construcción' => 'Termosellado sin costuras'],
                'is_featured' => true,
                'sku' => 'ADI-UCL-013',
            ],
            [
                'name' => 'Balón de Basketball Molten BG2000',
                'brand' => 'Molten',
                'model' => 'BG2000',
                'price' => 1099.00,
                'description' => 'Balón de basketball con cubierta de cuero sintético de alta calidad y gran agarre para juego en interior y exterior. Rebote consistente y durabilidad probada para entrenamientos exigentes.',
                'stock' => 30,
                'category' => 'Equipamiento de Basketball',
                'image' => 'catalogo-basketball2.jpg',
                'sizes' => [],
                'colors' => ['Naranja'],
                'material' => 'Cuero sintético',
                'gender' => 'unisex',
                'sport_type' => 'Basketball',
                'weight' => 0.58,
                'specifications' => ['Tamaño' => 'No. 7 oficial', 'Uso' => 'Interior y exterior'],
                'is_featured' => false,
                'sku' => 'MOL-BG2000-014',
            ],
            [
                'name' => 'Tenis Nike Downshifter 12 Running',
                'brand' => 'Nike',
                'model' => 'Downshifter 12',
                'price' => 1899.00,
                'description' => 'Tenis de running con soporte ligero y espuma de respuesta suave para tus kilómetros diarios. Malla transpirable y suela de caucho con tracción para asfalto y parque.',
                'stock' => 38,
                'category' => 'Equipamiento de Running',
                'image' => 'catalogo-running2.jpg',
                'sizes' => ['25', '26', '27', '28', '29'],
                'colors' => ['Naranja', 'Gris'],
                'material' => 'Mesh y espuma',
                'gender' => 'unisex',
                'sport_type' => 'Running',
                'weight' => 0.52,
                'specifications' => ['Pisada' => 'Neutra', 'Suela' => 'Caucho con tracción', 'Uso' => 'Asfalto y parque'],
                'is_featured' => false,
                'sku' => 'NIK-STR-015',
            ],
            [
                'name' => 'Par de Mancuernas Hexagonales 10 kg',
                'brand' => 'ProForm',
                'model' => 'Hexagonal 10',
                'price' => 1499.00,
                'description' => 'Par de mancuernas hexagonales de 10 kg con recubrimiento de caucho que protege el piso y evita que rueden. Agarre de acero cromado ergonómico para rutinas de fuerza en casa o gimnasio.',
                'stock' => 20,
                'category' => 'Equipamiento de Fitness',
                'image' => 'catalogo-fitness2.jpg',
                'sizes' => [],
                'colors' => ['Negro'],
                'material' => 'Hierro con caucho',
                'gender' => 'unisex',
                'sport_type' => 'Fitness',
                'weight' => 20.00,
                'specifications' => ['Peso' => '10 kg por mancuerna', 'Recubrimiento' => 'Caucho antirrodante', 'Agarre' => 'Acero cromado'],
                'is_featured' => false,
                'sku' => 'PFO-HEX10-016',
            ],
            [
                'name' => 'Traje de Baño Arena Competencia Hombre',
                'brand' => 'Arena',
                'model' => 'Competencia',
                'price' => 899.00,
                'description' => 'Traje de baño tipo jammer para competencia con tela resistente al cloro y ajuste de compresión que reduce la resistencia al agua. Costuras planas y cordón interno para máxima seguridad en el arranque.',
                'stock' => 26,
                'category' => 'Deportes Acuáticos',
                'image' => 'catalogo-natacion2.jpg',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Negro', 'Azul'],
                'material' => 'Poliéster resistente al cloro',
                'gender' => 'hombre',
                'sport_type' => 'Natación',
                'weight' => 0.12,
                'specifications' => ['Tipo' => 'Jammer competencia', 'Resistencia' => '100 horas de cloro', 'Ajuste' => 'Compresión'],
                'is_featured' => false,
                'sku' => 'ARE-JAM-017',
            ],
            [
                'name' => 'Pelotas de Tenis Wilson Championship (3 pzas)',
                'brand' => 'Wilson',
                'model' => 'Championship',
                'price' => 349.00,
                'description' => 'Bote de 3 pelotas de tenis con fieltro duradero y rebote consistente aprobado para juego recreativo y entrenamiento. Mantienen presión y rendimiento por más tiempo en todo tipo de canchas.',
                'stock' => 55,
                'category' => 'Deportes de Raqueta',
                'image' => 'catalogo-raqueta2.jpg',
                'sizes' => [],
                'colors' => ['Amarillo'],
                'material' => 'Fieltro y caucho',
                'gender' => 'unisex',
                'sport_type' => 'Tenis',
                'weight' => 0.18,
                'specifications' => ['Contenido' => '3 pelotas', 'Tipo' => 'Presurizadas', 'Uso' => 'Todo tipo de canchas'],
                'is_featured' => false,
                'sku' => 'WIL-CH3-018',
            ],
            [
                'name' => 'Mochila Nike Brasilia 9.5 (60 L)',
                'brand' => 'Nike',
                'model' => 'Brasilia 9.5',
                'price' => 1199.00,
                'description' => 'Mochila deportiva de gran capacidad con compartimento independiente para tenis o ropa sucia, múltiples bolsillos organizadores y respaldo acolchado ventilado. La compañera ideal para el gimnasio y los viajes.',
                'stock' => 24,
                'category' => 'Accesorios Deportivos',
                'image' => 'catalogo-accesorios2.jpg',
                'sizes' => [],
                'colors' => ['Negro', 'Gris'],
                'material' => 'Poliéster resistente',
                'gender' => 'unisex',
                'sport_type' => 'Fitness',
                'weight' => 0.90,
                'specifications' => ['Capacidad' => '60 L', 'Compartimento' => 'Para calzado', 'Respaldo' => 'Acolchado ventilado'],
                'is_featured' => false,
                'sku' => 'NIK-BRS95-019',
            ],
            [
                'name' => 'Bicicleta de Ruta Peugeot 700c',
                'brand' => 'Peugeot',
                'model' => 'Urbana 700c',
                'price' => 13999.00,
                'description' => 'Bicicleta de ruta con cuadro de aluminio ligero, rodada 700c y 21 velocidades para moverte en la ciudad o entrenar en carretera. Frenos de precisión y manubrio de ruta para una postura eficiente.',
                'stock' => 5,
                'category' => 'Ciclismo',
                'image' => 'catalogo-ciclismo2.jpg',
                'sizes' => [],
                'colors' => ['Blanco'],
                'material' => 'Aluminio',
                'gender' => 'unisex',
                'sport_type' => 'Ciclismo',
                'weight' => 11.50,
                'specifications' => ['Rodada' => '700c', 'Velocidades' => '21', 'Cuadro' => 'Aluminio ligero'],
                'is_featured' => true,
                'sku' => 'CAS-JER-020',
            ],
        ];

        foreach ($products as $data) {
            $category = $categories[$data['category']] ?? null;

            if (! $category) {
                $this->command->warn("Categoría no encontrada: {$data['category']}, se omite {$data['name']}");

                continue;
            }

            Product::updateOrCreate(
                ['sku' => $data['sku']],
                [
                    'name' => $data['name'],
                    'brand' => $data['brand'],
                    'model' => $data['model'],
                    'price' => $data['price'],
                    'description' => $data['description'],
                    'stock' => $data['stock'],
                    'category_id' => $category->id,
                    'image' => $this->resolveImage($data),
                    'sizes' => $data['sizes'],
                    'colors' => $data['colors'],
                    'material' => $data['material'],
                    'gender' => $data['gender'],
                    'sport_type' => $data['sport_type'],
                    'weight' => $data['weight'],
                    'specifications' => $data['specifications'],
                    'is_featured' => $data['is_featured'],
                ]
            );
        }
    }

    /**
     * Solo asigna la imagen si el archivo existe en el disco público.
     * Así la demo no muestra <img> rotos cuando aún no se suben los JPG;
     * las vistas ya renderizan un placeholder con image = null.
     * Al subir los archivos y re-ejecutar el seeder, la imagen se asigna.
     *
     * @param  array<string, mixed>  $data
     */
    private function resolveImage(array $data): ?string
    {
        $image = $data['image'] ?? null;

        if ($image && Storage::disk('public')->exists('products/'.$image)) {
            return $image;
        }

        if ($image) {
            $this->command->warn("Imagen no encontrada: products/{$image} ({$data['name']}), se usa placeholder.");
        }

        return null;
    }
}
