name: CI Laravel

on:
  push:
    branches: [ back-end ]
  pull_request:
    branches: [ back-end ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Ajusta la versión de PHP según tu proyecto
        extensions: mbstring, mysql, pdo, pdo_mysql, intl, xml, curl, json, gd, fileinfo
        ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Copy .env.example to .env.testing
      run: cp .env.example .env.testing

    - name: Configure .env.testing
      run: |
        php -r "
        \$path = '.env.testing';
        \$file = file_get_contents(\$path);
        \$file = preg_replace('/^APP_ENV=.*/m', 'APP_ENV=testing', \$file);
        \$file = preg_replace('/^APP_URL=.*/m', 'APP_URL=http://127.0.0.1', \$file);
        \$file = preg_replace('/^DB_CONNECTION=.*/m', 'DB_CONNECTION=mysql', \$file);
        \$file = preg_replace('/^DB_HOST=.*/m', 'DB_HOST=127.0.0.1', \$file);
        \$file = preg_replace('/^DB_PORT=.*/m', 'DB_PORT=3306', \$file);
        \$file = preg_replace('/^DB_DATABASE=.*/m', 'DB_DATABASE=test_db', \$file);
        \$file = preg_replace('/^DB_USERNAME=.*/m', 'DB_USERNAME=root', \$file);
        \$file = preg_replace('/^DB_PASSWORD=.*/m', 'DB_PASSWORD=root', \$file);
        \$file = preg_replace('/^SESSION_DRIVER=.*/m', 'SESSION_DRIVER=array', \$file);
        \$file = preg_replace('/^CACHE_DRIVER=.*/m', 'CACHE_DRIVER=array', \$file);
        \$file = preg_replace('/^QUEUE_CONNECTION=.*/m', 'QUEUE_CONNECTION=sync', \$file);
        \$file = preg_replace('/^MAIL_MAILER=.*/m', 'MAIL_MAILER=array', \$file);
        file_put_contents(\$path, \$file);
        "

    - name: Generate APP_KEY
      run: php artisan key:generate --env=testing

    - name: Clear caches
      run: |
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear

    - name: Wait for MySQL
      run: |
        sudo apt-get install -y netcat
        until nc -z -v -w30 127.0.0.1 3306
        do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Run migrations
      run: php artisan migrate --env=testing --force

    - name: Run database seeders
      run: php artisan db:seed --env=testing --force

    - name: Run tests
      run: php artisan test --env=testing -- --verbose
