name: CI Pipeline

on:
  push:
    branches: [ back-end ]
  pull_request:
    branches: [ back-end ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, mysqli, pdo, pdo_mysql
        ini-values: |
          memory_limit = 1G
        coverage: none

    - name: Install Dependencies
      run: composer install --no-progress --no-interaction --prefer-dist

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test
